# Introduction à MATLAB

Ce petit notebook parcourt l'essentiel des notions à connaitre pour une utilisation basique de Matlab.

MATLAB (MATrix LABoratory) est un logiciel et un langage de programmation associé créé par la société The MathWorks en 1984.

MATLAB (le logiciel) a la spécificité d'avoir une interface en ligne de commande qui permet d’exécuter des commandes simples. Des séquences de commandes peuvent être sauvegardés dans un fichier texte, typiquement avec l’éditeur MATLAB, sous la forme d’un « script » ou encapsulé dans une fonction. L'exécution d'un script se déroulant comme une exécution ligne à ligne des commandes contenues dans le script. On dit que MATLAB est un langage interprété (au contraire de compiler).

**Remarque :** la combinaison des touches [Maj]+[Enter] évalue la cellule et passe à la suivante.

# Prise en main et interface

![alt text](http://www.cs.uic.edu/~jbell/CourseNotes/Matlab/images/Environment.jpg "MATLAB sur le bureau")

# La console (Command window)

La spécificité de MATLAB et son interaction en ligne de commande avec une manipulation simple comme une calculatrice.

In [ ]:
help help

In [ ]:
lookfor eye

## Opérations arithmétiques usuelles : +, -, *, /, \, ^

In [1]:
2+2^3-3*6 % expression classique

ans =

    -8

In [3]:
1/2  % division à droite 
2\1  % division à gauche !!!

ans =

    0.5000


ans =

    0.5000

In [4]:
(1+3)^2/4 % quel est le résultat ?
(1+3)/2^4 % idem

ans =

     4


ans =

    0.2500

In [5]:
-(4)/2/2*3 % une idée sur le résultat ?
-4*3/2/2 

ans =

    -3


ans =

    -3

Les expressions sont évaluées de gauche vers la droite avec l'ordre de priorité suivant :

| Niveau | Opération |
|:-:|:-|
|1 |Parenthèses $()$ |
|2 |Transpose ($.'$), puissance (.^), conjuguée complexe ($'$), puissance de matrice (^)|
|3 |plus unitaire (+), moins unitaire (-), negation logique (~)|
|4 | Multiplication ($.*$), division à droite (./), division à gauche (.\), multiplication matricielle ($*$), division matricielle à droite (/), division matricielle à gauche ($\backslash$)|
|5 | Addition (+), soustraction (-)|
|6 |Operateur colonne (:)|
|7 |plus petit que (<), plus petit ou égal (<=), plus grand que (>), plus grand ou égal (>=), égal à (==), pas égal à (~=)|
|8 | ET (AND) logique élément par élément (&)|
|9 | OU (OR) logique élément par élément ($|$)|
|10 |Short-circuit AND (&&)|
|11 |Short-circuit OR ($||$)|

## Les fonctions scientifiques :

| fonctions ||
|:-:|:-|
|abs()| Valeur absolue ou module|
|acos()| Cosinus inverse|
|acosh()| Cosinus inverse hyperbolique|
|asin()| Sinus inverse|
|asinh()| Sinus inverse hyperbolique|
|atan()| Tangente inverse|
|atanh()| Tangente inverse hyperbolique|
|cos()| Cosinus (en radian)|
|cosh()| Cosinus hyperbolique|
|cotg()| Cotangente (en radian)|
|coth()| Cotangente hyperbolique|
|erf()| Fonction erreur : erf(x)=$\frac{1}{\sqrt{2\pi}}\int_{-\infty}^x e^{-t^2} dt$|
|erfc()| Fonction erreur complementaire ´ : erfc(x)=1-erf(x)|
|exp()| Exponentielle|
|gamma()| Fonction $\Gamma(x)=\int_0^{+\infty} t^{x-1}e^{-t}dt$
|gammaln()| Logarithme de la fonction $\Gamma$|
|log()| Logarithme nepérien |
|log10()| Logarithme decimal |
|log2()| Logarithme binaire |
|sign()| Fonction signe|
|sin()| Sinus (en radian)|
|sinh()| Sinus hyperbolique|
|sqrt()| Racine carrée|
|tan()| Tangente (en radian)|
|tanh()| Tangente hyperbolique|

In [6]:
log(exp(0)) % logarithme népérien
log10(10) % logaritme décimal

ans =

     0


ans =

     1

In [7]:
sign(-sqrt(2)) % fonction sign
sign(0)
sign(2)

ans =

    -1


ans =

     0


ans =

     1

| fonctions d'arrondi||
|:-:|:-|
|ceil()| Partie entiere "par exces"|
|fix()| Partie entiere "la plus proche de 0"|
|floor()| Partie entiere "inferieure"|
|round()| Arrondi à l’entier le plus proche|


In [ ]:
ceil(0.6)
ceil(-0.6)
fix(0.6)

## Variables prédéfinies :

In [8]:
format long  % pour afficher 15 déciales
pi
sin(pi) % presque 0....
sin(pi/2)
format short % seulement 5 décimales à l'affichage

ans =

   3.141592653589793


ans =

     1.224646799147353e-16


ans =

     1

In [9]:
eps  %la précision relative des calculs en virgule flottante sous Matlab
1+eps/2==1 % cette égalité est vraie !

ans =

   2.2204e-16


ans =

     1

In [10]:
realmax
realmin

ans =

  1.7977e+308


ans =

  2.2251e-308

In [11]:
1/inf  % inf représente l'infinie
1/0   % certaines opérations sont permises...
inf/0

ans =

     0


ans =

   Inf


ans =

   Inf

In [13]:
1/inf
inf+1
inf*4

ans =

     0


ans =

   Inf


ans =

   Inf

In [14]:
inf/inf % les formes indéterminées restent
inf*0

ans =

   NaN


ans =

   NaN

## Calcul complexe

In [15]:
i  %variable prédéfinit (i)^2=-1
sin(i) % une extension naturelle des fonctions aux complexes
log(i)
(1+i)^i

ans =

   0.0000 + 1.0000i


ans =

   0.0000 + 1.1752i


ans =

   0.0000 + 1.5708i


ans =

   0.4288 + 0.1549i

In [16]:
sqrt(-1) % attention de fait ici il n'y a pas d'erreur

ans =

   0.0000 + 1.0000i

In [17]:
imag(i)  % partie imaginaire

ans =

     1

In [18]:
real(i)  % partie réelle

ans =

     0

In [19]:
abs(1+i) % module

ans =

    1.4142

## Les booléens :

Sous MATLAB le booléen (1 bit) est composé des deux valeurs 0 (faux) et 1 (vrai), par extension toute valeur non nulle est considérée comme vrai.

Opérateurs de comparaison : 

| symbole | fonction |
|:-:|-|
|a<b| a stritement inférieur à b|
|a<=b| a inféieur ou égale à b|
|a>b| a stritement supérieur à b|
|a>=b| a supérieur ou égale à b|
|a==b| a égale à b |
|a~=b| a différent de b|

Opérateurs logiques :

| symbole | fonction |
|:-:|-|
| & | et (AND) |
| $|$ | ou (OR)|
| ~| négation (NOT)|

In [24]:
(1<2) & 3

ans =

     1

In [21]:
2==3
2~=3
2>=3
2>3

ans =

     0


ans =

     1


ans =

     0


ans =

     0

In [23]:
(1&0)|2

ans =

     1

| |Fonctions booléennes (logical) 
|-|-|
|all() |Vrai si tous les éléments d’un vecteur sont non nuls|
|any()| Vrai si au moins un élément d’un vecteur est non nul|
|exist()| Vérifie si une variable ou une fonction existe |
|find()| Retourne les indices des élélements non nuls|
|isempty()| Vrai pour matrice vide|
|isinf()| Vrai pour élément infini|
|isnan() | Vrai pour NaN (Not-a-Number)|
|issparse() | Vrai pour matrice creuse |
|isstr() | Vrai pour chaine de caractère|

## Les chaines de caractère

la simple quote (') délimite une chaine de caractère

In [27]:
txt='une chaine'

txt =

une chaine

Cette chaine est gérée comme un tableau avec des indices commançant à 1

In [28]:
length(txt)

ans =

    10

la quote (') est aussi un caractère il faut la doubler dans sa déclaration

In [29]:
txt2='c''est une vraie chaine'

txt2 =

c'est une vraie chaine

On peut convertir un nombre en chaine de caractère

In [31]:
tt=num2str(sqrt(2))

tt =

1.4142

Concaténer (mettre bout à bout) deux chaines

In [32]:
txt=['racine de 2 vaut : ', num2str(sqrt(2))]

txt =

racine de 2 vaut : 1.4142

Il est également possible d'évaluer une chaine de caractère 

In [33]:
txt='1+2'
eval(txt)

txt =

1+2


ans =

     3

## Les variables :

In [34]:
a=1 % pas de déclaration préalable le = d'affectaion suffit
b=a+1

a =

     1


b =

     2

In [35]:
a=(1>2)

a =

     0

In [36]:
a='une chaine de caractere'

a =

une chaine de caractere

In [38]:
A=2
a=3% les noms des variables commencent par une lettre de l'alphabet avec une distinction majuscule minuscule
A==a  % les signes $,?,!...sont interdits
A_23=1

A =

     2


a =

     3


ans =

     0


A_23 =

     1

### Gestions des variables

In [39]:
whos % renvois la liste des variables utilisées 

Name      Size            Bytes  Class      Attributes

  A         1x1                 8  double               
  A_23      1x1                 8  double               
  a         1x1                 8  double               
  ans       1x1                 1  logical              
  b         1x1                 8  double               
  tt        1x6                12  char                 
  txt       1x3                 6  char                 
  txt2      1x22               44  char

In [40]:
who

Your variables are:

A     A_23  a     ans   b     tt    txt   txt2

In [ ]:
save 'monfichier.mat' A % sauvegarde d'une variable dans un fichier

In [ ]:
clear A % efface la variable A de la mémoire
clear   % efface toutes les variables

In [ ]:
whos 
load 'monfichier.mat' % charge la variable A contenue dans le fichier
whos

## Tableaux et matrices :

In [44]:
a=[2,3 4 7 9]  % constructeur en ligne
b=[2;3;4;7;9]  % constructeur en colonne
a=[a ; a ; 2 3 4 5 6]    % concatenation
A=[]           % tableau vide

a =

     2     3     4     7     9


b =

     2
     3
     4
     7
     9


a =

     2     3     4     7     9
     2     3     4     7     9
     2     3     4     5     6


A =

     []

In [45]:
A=[1 2; 3,4]    % une matrice 2x2
A=[A A ; 1 7 3 4]  % concatenation par bloc

A =

     1     2
     3     4


A =

     1     2     1     2
     3     4     3     4
     1     7     3     4

In [46]:
A=zeros(3,4)  % création d'une matrice nulle de taille 3x4
B=ones(4,3)   % création d'une matrice unité de taille 4x3
C=rand(2,2)   % réation d'une matrice 2x2 de coefficients aléatoires de loi uniforme entre 0 et 1
D=eye(3,4)    % création d'une matrice identité de taille 3x4

A =

     0     0     0     0
     0     0     0     0
     0     0     0     0


B =

     1     1     1
     1     1     1
     1     1     1
     1     1     1


C =

    0.8147    0.1270
    0.9058    0.9134


D =

     1     0     0     0
     0     1     0     0
     0     0     1     0

In [48]:
size(A)      % retourne la dimension n x m de A (sous forme d'un vecteur ligne)
size(A,1)    % nombre de ligne
size(A,2)    % nombre de colonnes 
length(A)    % nombre total d'éléments in 3*4

ans =

     3     4


ans =

     3


ans =

     4


ans =

     4

## Constructeur a:b , linspace ...

In [58]:
a=1:7:100; % constructeur début:fin  de début jusqu'à fin par incrément de 1

In [59]:
a

a =

  Columns 1 through 13

     1     8    15    22    29    36    43    50    57    64    71    78    85

  Columns 14 through 15

    92    99

In [60]:
a=1:2:8 % de 1 jusqu'à 8 par pas de 2 (la borne 8 n'est pas incluse)
a=0:sqrt(2)/2:3 % par pas de 0.7071 

a =

     1     3     5     7


a =

         0    0.7071    1.4142    2.1213    2.8284

In [63]:
a=5:1    % Attention résultat surprenant
a=5:-1:1 % peut être le résultat escompté ?
a=5:-sqrt(2)/2:0

a =

   Empty matrix: 1-by-0


a =

     5     4     3     2     1


a =

  Columns 1 through 7

    5.0000    4.2929    3.5858    2.8787    2.1716    1.4645    0.7574

  Column 8

    0.0503

In [61]:
a=0:1/3+eps:1 % la borne supérieur 1 n'est pas prise

a =

         0    0.3333    0.6667

In [65]:
a=linspace(0,1,4) % Une alternative linspace(début,fin,nombre de points)
size(a)

a =

         0    0.3333    0.6667    1.0000


ans =

     1     4

In [64]:
b=logspace(1,2,4) % même chose en échelle log
log10(b)

b =

   10.0000   21.5443   46.4159  100.0000


ans =

    1.0000    1.3333    1.6667    2.0000

## Manipulation des tableaux (vecteurs)
### Extraction

In [79]:
a=linspace(0,1,4) 
a(1)         % les tableaux commencent à 1
a(2)
a(end)       % end permet de ne pas connaitre a priori la taille du tableau
a(end-1)     % l'avant dernier
a(1:2:3)       % les deux premier termes
a(end:-1:1)  % on inverse l'ordre du tableau
a(end:1)     % attention...
a(2*ones(3,1))
a(1.0)

a =

         0    0.3333    0.6667    1.0000


ans =

     0


ans =

    0.3333


ans =

     1


ans =

    0.6667


ans =

         0    0.6667


ans =

    1.0000    0.6667    0.3333         0


ans =

   Empty matrix: 1-by-0


ans =

    0.3333    0.3333    0.3333


ans =

     0

### Affectation

In [82]:
a(1)=-100       
a(2)=0
a(end-1)=10
a(1:2)=0
a(1:2)=a(3:4)
a(15)=sqrt(2)

a =

 -100.0000    1.0000   10.0000    1.0000    1.4142


a =

 -100.0000         0   10.0000    1.0000    1.4142


a =

 -100.0000         0   10.0000   10.0000    1.4142


a =

         0         0   10.0000   10.0000    1.4142


a =

   10.0000   10.0000   10.0000   10.0000    1.4142


a =

  Columns 1 through 7

   10.0000   10.0000   10.0000   10.0000    1.4142         0         0

  Columns 8 through 14

         0         0         0         0         0         0         0

  Column 15

    1.4142

### Suppression d'éléments

In [89]:
%a(end)=[]
%a(5:14)=[]
b=1:5
%b(1:2:end)=[]
%b(1)

b =

     1     2     3     4     5

## Fonctions vectorielles

||Opérations vectorielles élémentaires|
|-|-|
|cumprod()| Produits cumulés des composantes|
|cumsum()| Sommes cumulées des composantes|
|max() |Plus grande composante|
|mean() |Moyenne des composantes|
|median()| Médiane des composantes|
|min() |Plus petite composante|
|prod() |Produit des composantes|
|sort() |Tri des composantes|
|std() |Ecart type des composantes|
|sum() |Somme des composantes|


In [91]:
b'
sum(b)
cumsum(b)
prod(b)
cumprod(b)
max(b)
min(b)
[m,k]=min(b)

ans =

     1
     2
     3
     4
     5


ans =

    15


ans =

     1     3     6    10    15


ans =

   120


ans =

     1     2     6    24   120


ans =

     5


ans =

     1


m =

     1


k =

     1

In [95]:
a=rand(5,1)
[res,ind]=sort(a)
%a(ind)

a =

    0.9595
    0.6557
    0.0357
    0.8491
    0.9340


res =

    0.0357
    0.6557
    0.8491
    0.9340
    0.9595

In [98]:
c=1:0.2:2
c+1
c*2

c =

    1.0000    1.2000    1.4000    1.6000    1.8000    2.0000


ans =

    2.0000    2.2000    2.4000    2.6000    2.8000    3.0000


ans =

    2.0000    2.4000    2.8000    3.2000    3.6000    4.0000

In [101]:
sin(c)

ans =

    0.8415    0.9320    0.9854    0.9996    0.9738    0.9093

In [113]:
d=0:0.2:1
c
c.*c
c*c'
c.^2
d./c
2.^(1:6)
d-c

d =

         0    0.2000    0.4000    0.6000    0.8000    1.0000


c =

    1.0000    1.2000    1.4000    1.6000    1.8000    2.0000


ans =

    1.0000    1.4400    1.9600    2.5600    3.2400    4.0000


ans =

   14.2000


ans =

    1.0000    1.4400    1.9600    2.5600    3.2400    4.0000


ans =

         0    0.1667    0.2857    0.3750    0.4444    0.5000


ans =

     2     4     8    16    32    64


ans =

   -1.0000   -1.0000   -1.0000   -1.0000   -1.0000   -1.0000

In [116]:
rand(1,6)>sqrt(2)/2

ans =

     0     0     1     0     0     0

In [117]:
whos

Name      Size            Bytes  Class      Attributes

  A         3x4                96  double               
  A_23      1x1                 8  double               
  B         4x3                96  double               
  C         2x2                32  double               
  D         3x4                96  double               
  a         5x1                40  double               
  ans       1x6                 6  logical              
  b         1x5                40  double               
  c         1x6                48  double               
  d         1x6                48  double               
  ind       5x1                40  double               
  k         1x1                 8  double               
  m         1x1                 8  double               
  res       5x1                40  double               
  tt        1x6                12  char                 
  txt       1x3                 6  char                 
  txt2      1x22               4

In [119]:
a=rand(1,6)
a>0:0.1:0.5
a~=a
a==1/5

a =

    0.7094    0.7547    0.2760    0.6797    0.6551    0.1626


ans =

     1     1     1     1     1     0


ans =

     0     0     0     0     0     0


ans =

     0     0     0     0     0     0

In [123]:
a=rand(1,5)
a>0.5
a(a>0.5)  % compression

a =

    0.7184    0.9686    0.5313    0.3251    0.1056


ans =

     1     1     1     0     0


ans =

    0.7184    0.9686    0.5313

In [126]:
b=['a' 'bc']

b =

abc

In [133]:
b(1:end-1)

ans =

ab

In [128]:
size(b)

ans =

     1     3

In [129]:
length(b)

ans =

     3

In [131]:
d=[b;b]

d =

abc
abc

In [134]:
b'

ans =

a
b
c

# les Matrices

In [145]:
A=round(10*rand(4,4))

A =

     7     8     6     6
     2     2     7     6
     9     3     5     7
     3     1     4     6

In [147]:
find(A==7)
[I,J]=find(A==7)

ans =

     1
    10
    15


I =

     1
     2
     3


J =

     1
     3
     4

In [141]:
A(1,1:end)
A(1,end)
A(1)
A(6)
find(A==A(1,1)) %
[I,J]=find(A==A(1,3)) % position des valeurs egales a 4

ans =

    0.1555   -0.3086    0.0458    1.8140


ans =

    1.8140


ans =

    0.1555


ans =

   -1.0966


ans =

     1


I =

     1


J =

     3

In [149]:
A(1,1:end) % 1ere ligne
A(1,:)
A(1:2,1:2) % 1 er bloc des lignes 1,2 et colonnes 1,2  
A([1 1],1:2)


ans =

     7     8     6     6


ans =

     7     8     6     6


ans =

     7     8
     2     2


ans =

     7     8
     7     8

In [150]:
A(1,1:end)=1 
A(1,:)=2
A(1:2,1:2)=0
A(1:2,1:2)=A([1 1],[3 4])

A =

     1     1     1     1
     2     2     7     6
     9     3     5     7
     3     1     4     6


A =

     2     2     2     2
     2     2     7     6
     9     3     5     7
     3     1     4     6


A =

     0     0     2     2
     0     0     7     6
     9     3     5     7
     3     1     4     6


A =

     2     2     2     2
     2     2     7     6
     9     3     5     7
     3     1     4     6

In [152]:
A=zeros(3,4)
B=ones(4,3)
%C=rand(2,2)
%D=eye(3,4)
A*B
B'
B'.*A

A =

     0     0     0     0
     0     0     0     0
     0     0     0     0


B =

     1     1     1
     1     1     1
     1     1     1
     1     1     1


ans =

     0     0     0
     0     0     0
     0     0     0


ans =

     1     1     1     1
     1     1     1     1
     1     1     1     1


ans =

     0     0     0     0
     0     0     0     0
     0     0     0     0

## Fonctions Matricielles 

| Fonction| |
|:-:|-|
|cond() |Conditionnement|
|det() |Déterminant
|norm() |Norme 1, 2, Frobenius, ∞|
|rank() |Rang|
|trace()|Trace|
|chol() |Factorisation de Cholesky|
|inv() |Inverse|
|lu() | Factorisation LU|
|qr() |Factorisation QR|
|eig()|Valeurs propres et vecteurs propres|
|poly() |Polynôme caractéristique|
|svd() |Sécomposition en valeurs singulières|
|expm() |exponentielle de matrice|
|sqrtm() |racine carrée de matrice|
| \ ou / | Résolution matricielle |

In [159]:
A=[1 2;1 2]
inv(A)
b=[1;1]
x=A\b


A =

     1     2
     1     2

[Warning: Matrix is singular to working precision.] 
[> In pymat_eval (line 31)
  In matlabserver (line 24)] 

ans =

   Inf   Inf
   Inf   Inf


b =

     1
     1

[Warning: Matrix is singular to working precision.] 
[> In pymat_eval (line 31)
  In matlabserver (line 24)] 

x =

   NaN
   NaN

In [163]:

C=rand(2,2)
%C^2
%C.^2
%C./[2 2; 3 3]
inv(C)
C^(-1)
trace(C)
[V,D]=eig(C)   %V est une matrice dont les colonnes sont les composantes des vecteurs propres
               % D est une matrice dont les diagonales sont les valeurs propres. 
%norm(C*V(:,1)-l(1,1)*V(:,1))
%norm(C,inf)

C =

    0.6135    0.5407
    0.5822    0.8699


ans =

    3.9754   -2.4711
   -2.6607    2.8034


ans =

    3.9754   -2.4711
   -2.6607    2.8034


ans =

    1.4834


V =

   -0.7705   -0.6092
    0.6374   -0.7930


D =

    0.1661         0
         0    1.3173

In [ ]:
sin(C)

|| Manipulation de matrices |
|-|-|
|diag |Crée ou extrait une matrice diagonale |
|fliplr | Permutte les colonnes d’une matrice |
|flipud |Permutte les lignes d’une matrice |
|reshape |Modifie la taille d’une matrice|
|rot90 |Rotation de 90° dans le sens trigonométrique|
|tril |Extrait une matrice triangualaire inférieure|
|triu |Extrait une matrice triangualaire supérieure|

In [167]:
A=rand(3,4)
B=reshape(A,4,3)

A =

    0.5201    0.5861    0.7549    0.6878
    0.3477    0.2621    0.2428    0.3592
    0.1500    0.0445    0.4424    0.7363


B =

    0.5201    0.2621    0.4424
    0.3477    0.0445    0.6878
    0.1500    0.7549    0.3592
    0.5861    0.2428    0.7363

In [171]:
a=1:25;
a=reshape(a,5,5)

a =

     1     6    11    16    21
     2     7    12    17    22
     3     8    13    18    23
     4     9    14    19    24
     5    10    15    20    25

In [174]:
diag(a,1)

ans =

     6
    12
    18
    24

In [176]:
diag(1:5)

ans =

     1     0     0     0     0
     0     2     0     0     0
     0     0     3     0     0
     0     0     0     4     0
     0     0     0     0     5

In [177]:
triu(A)

ans =

    0.5201    0.5861    0.7549    0.6878
         0    0.2621    0.2428    0.3592
         0         0    0.4424    0.7363

## Graphiques

In [ ]:
%plot -s 1600,800

In [ ]:
f=figure();
t=0:0.1:20;
plot(t,sin(t))
xlabel('Time(sec)')
ylabel('y')
title('Un exemple')

| | Graphique 2D |
|-|-|
|bar() |Diagramme en barres|
|fplot() | Graphe de fonction|
|grid() |Quadrillage|
|hist() |Histogramme|
|plot() |Graphe 2D|
|polar() |Graphe en coordonnées polaires|
|title() |Titre de graphique|
|xlabel() | Légende axe horizontal|
|ylabel() |Légende axe vertical|
|legends() | Nom des courbes|

In [ ]:
x=0:0.1:3*pi ; y=sin(x); z=cos(x);
subplot(221)
plot(x(1:3:end),x(1:3:end).^2,'c*')
title('x et y')
subplot(222)
plot(x,y)
title('x et y')
subplot(223)

plot(x,z)
title('x et z')
subplot(224)
plot(x, y, 'r-', x, z, 'g-')
title('x et [y z]')

# Exercices

**Exercice 0** 

1. Ecrire le vecteur (1 2 4), obtenir sa transposee.

2. Calculer le module est l’argument de $\dfrac{1}{1+2i}$

6.  Entrer les matrices :
$$
A=\left(
\begin{array}{ccc}
1 & 2 & 2\\
0 & 1 & 2\\
0 & 0 & 1
\end{array}  \right) \quad
B=\left(
\begin{array}{ccc}
0 & 1 & 1\\
1 & 0 & 1\\
1 & 1 & 0
\end{array}  \right)
$$

Faire le produit matriciel $A \times B$, puis multiplier terme à terme $A$
et la transposée de $B$.

**Exercice 1**

Soit A = [1:4 ; 5:8 ; 9:12 ; 13:16] 

1. Quel est le résultat de l’instruction A(10:-1:5) ?

2. Comment créer un vecteur contenant les éléments de A dans l’ordre suivant : 16 12 8 4 15 11 ?

3. Quel est le résultat de l’instruction [A(1,:),5] ? 

4. Comment créer un vecteur contenant les éléments de A dans l’ordre suivant : 1 2 3 4 5 ?

5. Quel est le résultat de diag(diag(A)) ?

**Exercice 2** Créer une matrice de ce type


         0         0         0         0         0
         0   -0.1774    0.2916   -0.8045         0
         0   -0.1961    0.1978    0.6966         0
         0    1.4193    1.5877    0.8351         0
         0         0         0         0         0
         
les éléments de la matrice 3×3 centrale étant choisit suivant une loi normale centrée réduite.

**Exercice 3** Soit $M = magic(4)$. Comment expliquer le résultat de l’instruction M(M) ?

**Exercice 4** Créer un vecteur des puissances de 2 de 0 à 16 (2^0, 2^1...).

**Exercice 5** Créer une matrice 10×4, contenant les puissances de 0 à 9 des nombres 2, 3, 4 et 5.

**Exercice 6** Quel est le résultat de l’instruction suivante ?
M = [1 2 3; 4 5 6; 7 8 9];
M ~= diag(diag(M))

**Exercice 7** Créer une matrice triangulaire supérieur de dimension 10×10 avec seulement
des 1 dans sa partie supérieure.



## Eléments de programmation

if .. then else

In [ ]:
a=2
if a>1 ; b=2 ,end

if a>3 
   b=1
else
   b=0
end

if a>1 
   b=2
elseif a<6
   b=0
elseif a<5
   b=-4
else
   b=10
end

if a>1 
   b=2
elseif a<6
   b=0
end


In [ ]:
i=1
while i<6
     i=i+0.34
end

In [ ]:
for i=1:3
  disp(i)
end
disp('###############')
for i=[2 7 8]
    disp(i)
end
disp('###############')
for i=rand(1,3)
    disp(i)
end
disp('###############') 
for i=[2 7 8;-2 -7 -8]
    disp(i)
end 
disp('###############')
for i=[2;7;8]
    disp(i)
end

## Fonctions

In [ ]:
**Exercice 8** Que fait cet algorithme (crible d'Eratosthene)
n = 49;
T = ones(1,n);
for k = 2:sqrt(n)
if T(k)==1
T(2*k:k:n)=0;
end
end
find(T)